---
title: "data_cleaning"
format: pdf
editor: visual
---

## Data cleaning (hej hej)

```{r}
library(dplyr)
```

```{r}
# load data sets: Milou

# # Skapa en mapp för att packa upp
# outdir <- "ADNIMERGE2_unpacked"
# dir.create(outdir, showWarnings = FALSE)
# 
# # Packa upp tar.gz-filen
# untar("ADNIMERGE2.tar.gz", exdir = outdir)
# 
# # Plasma-biomarkörer
# load(file.path(outdir, "ADNIMERGE2/data/UPENN_PLASMA_FUJIREBIO_QUANTERIX.rda"))
# plasma_data <- UPENN_PLASMA_FUJIREBIO_QUANTERIX
# 
# # Amyloid-PET
# load(file.path(outdir, "ADNIMERGE2/data/UCBERKELEY_AMY_6MM.rda"))
# amyloid_data <- UCBERKELEY_AMY_6MM
# 
# # Diagnos
# load(file.path(outdir, "ADNIMERGE2/data/DXSUM.rda"))
# diagnosis_data <- DXSUM
```

```{r}
# load data sets: Charley

# loading adni library
library(ADNIMERGE2)

# biomarker data set
plasma_data = UPENN_PLASMA_FUJIREBIO_QUANTERIX

# PET scan data
amyloid_data = UCBERKELEY_AMY_6MM

# dx data
diagnosis_data = DXSUM
```

```{r}
cat("Plasma-data unika RID:", length(unique(plasma_data$RID)), "\n")
cat("Amyloid-PET-data unika RID:", length(unique(amyloid_data$RID)), "\n")
cat("Diagnos-data unika RID:", length(unique(diagnosis_data$RID)), "\n")
```

```{r}
# selecting the relevant variables -> why these ones???
plasma_data = plasma_data %>% select(
  "ORIGPROT", "COLPROT", "RID", "VISCODE2", "EXAMDATE", "pT217_F", "AB42_F",
  "AB40_F", "AB42_AB40_F", "pT217_AB42_F", "NfL_Q", "GFAP_Q")

diagnosis_data = diagnosis_data %>% select("ORIGPROT", "COLPROT", "RID", "VISCODE2",
                                           "EXAMDATE", "DIAGNOSIS")

# merging the plasma data set and the diagnosis data set by RID (unique identifier)
merged = plasma_data %>%
  merge(diagnosis_data, by = "RID", suffix = c("_plasma", "_dx"))

# checking whether there are any observations that should be removed as per the ADNI leadership guidelines about observations with PTID in the format "381_S_10###"
grep("381_S_10###", merged$PTID)
```

```{r}
test = merged %>%
#   grouping by the unique identifier
  group_by(RID) %>%
#   extracting only rows with the most recent diagnosis exam date
  slice_max(EXAMDATE_dx) %>%
#   and the earlier plasma exam date (for baseline)
  slice_min(EXAMDATE_plasma) %>%
#   creating a new variable event, 1 = AD, 0 otherwise
  mutate(event = case_when(
    DIAGNOSIS == "Dementia" ~ 1,
    TRUE ~ 0
  ))

# some patients have a first observation that is not "bl", it seems to be that this is the case even in the original plasma data set so might not be a coding problem but let's try and check this!
```

```{r}
# some duplicate RIDs, why is this?
length(unique(test$RID))
length(test$RID)
```

```{r}
# We want to check how many obs we have going from CN -> AD: if this is low we need to take in to account going from CN -> MCI, MCI -> AD, CN -> AD

# creating a data frame with only the baseline diagnosis for each patient and creating an event variable which describes whether diagnosis changes from CN/MCI -> AD
first_dx = merged %>% group_by(RID) %>%
  filter(EXAMDATE_dx == min(EXAMDATE_dx)) %>%
  mutate(event = case_when(
    DIAGNOSIS == "Dementia" ~ 1,
    TRUE ~ 0
  ))

# creating a data frame with only the last diagnosis for each patient and creating an event variable which describes whether diagnosis changes from CN/MCI -> AD
last_dx = merged %>% group_by(RID) %>%
  filter(EXAMDATE_dx == max(EXAMDATE_dx)) %>%
    mutate(event = case_when(
    DIAGNOSIS == "Dementia" ~ 1,
    TRUE ~ 0
  ))

# merging the two data frames with the first and last and recoding diagnosis as 1 = AD, 0 otherwise in order to compare the first and last values
first_last_dx = merge(
#   merging the data set of first and last diagnoses by RID 
  first_dx, last_dx,by = "RID", suffix = c("_first", "_last")) %>%
#   arranging by ascending RID to check format
  arrange(RID) %>%
#   adding a variable to check whether the diagnosis changed from CN/MCI to AD
  mutate(dx_change = event_first != event_last)

# count how many obs have change in diagnosis from CN to AD
table(first_last_dx$dx_change)
```
