---
title: "Test"
format: pdf
editor: visual
---

```{r}
# loading libraries
library(dplyr)
library(JMbayes2)
library(lme4) # decide which package will we use for lme
library(nlme) # decide which package will we use for lme
library(survival)
library(ggplot2)
```

```{r}
# Milou
load("ADNIMERGE2_unpacked/ADNIMERGE2/data/BLENNOWPLASMANFLLONG.rda")
nfl_data <- BLENNOWPLASMANFLLONG
# 
load("ADNIMERGE2_unpacked/ADNIMERGE2/data/UGOTPTAU181.rda")
ptau_data <- UGOTPTAU181
#  
load("ADNIMERGE2_unpacked/ADNIMERGE2/data/DXSUM.rda")
diagnosis_data <- DXSUM
#  
load("ADNIMERGE2_unpacked/ADNIMERGE2/data/PTDEMOG.rda")
demographics <- PTDEMOG
# 
load("ADNIMERGE2_unpacked/ADNIMERGE2/data/APOERES.rda")
apoe <- APOERES
```

```{r}
# We select the required nfl variables
nfl_data <- nfl_data %>%
  select(RID, VISCODE2, EXAMDATE, PLASMA_NFL)

# We select the required ptau variables
ptau_data <- ptau_data %>%
  select(RID, VISCODE2, EXAMDATE, PLASMAPTAU181)

# We select the required diagnosis variables
diagnosis_data <- diagnosis_data %>%
  select(ORIGPROT, COLPROT, RID, VISCODE2, EXAMDATE, DIAGNOSIS)

# We add _dx on the diagnosis variables 
diagnosis_data_dx <- diagnosis_data %>%
  rename_with(~paste0(.x, "_dx"), -c(RID, VISCODE2))

# We merge NFL, ptau och diagnosis
merged_data <- nfl_data %>%
  left_join(ptau_data, by = c("RID", "VISCODE2"), suffix = c("_nfl", "_ptau")) %>%
  left_join(diagnosis_data_dx, by = c("RID", "VISCODE2"))
```

```{r}
# We only keep the demographics variables we need and one row per person 
demographics_small <- demographics %>%
  select(RID, PTDOBYY, PTGENDER) %>%
  distinct(RID, .keep_all = TRUE)

# We merge with merged_data
merged_data <- merged_data %>%
  left_join(demographics_small, by = "RID")

# We make sure that gender is a factor 
merged_data$PTGENDER <- as.factor(merged_data$PTGENDER)

# We create a variable for apoe4 status
apoe$APOE4_status <- ifelse(apoe$GENOTYPE %in% c("2/4","3/4","4/4"), 1, 0)

# We merge apoe with merged_data 
merged_data <- merge(merged_data, apoe[, c("RID", "APOE4_status")], by="RID")
```

```{r}
# We filter individuals with at least 3 measurements
keep = unique((ptau_data %>% group_by(RID) %>% filter(n() > 2))$RID)
merged_data <- merged_data %>% filter(RID %in% keep)

# We check number of individuals with at least 3 measurements 
length(keep)
```

```{r}
# We create a baseline-date
merged_data <- merged_data %>%
  group_by(RID) %>%
  mutate(baseline_date = min(EXAMDATE_ptau)) %>%
  ungroup()

# We create event and time_to_event (where dementia is the event) and add age och gender 
surv_data <- merged_data %>%
group_by(RID) %>%
  summarise(
    age_at_baseline = as.numeric(min(baseline_date), "%Y") - min(PTDOBYY),
    PTGENDER = PTGENDER[which.min(EXAMDATE_ptau)],
    APOE4_status = APOE4_status[which.min(EXAMDATE_ptau)],
    
    time_to_event = case_when(

    any(DIAGNOSIS_dx == "Dementia") ~
      as.numeric(min(EXAMDATE_ptau[DIAGNOSIS_dx == "Dementia"]) -
                   min(c(EXAMDATE_ptau, EXAMDATE_dx))),

    TRUE ~ as.numeric(max(c(EXAMDATE_ptau, EXAMDATE_dx)) -
                    min(c(EXAMDATE_ptau, EXAMDATE_dx)))) / 365,

  event = as.integer(any(DIAGNOSIS_dx == "Dementia"))
) %>% ungroup()

# We put the survival data back into the merged_data
merged_data <- merged_data %>%
  left_join(surv_data, by = "RID")

# We check the number of events 
table(surv_data$event)
```

```{r}
# We create time_years (time from baseline)
merged_data <- merged_data %>%
  mutate(time_years = as.numeric(EXAMDATE_ptau - baseline_date) / 365.25)
```

```{r}
# We log transform the biomarkers 
merged_data$log_PLASMAPTAU181 <- log(merged_data$PLASMAPTAU181)
merged_data$log_PLASMA_NFL <- log(merged_data$PLASMA_NFL)
```

```{r}
# We remove missing values 
merged_data <- na.omit(merged_data)
surv_data <- na.omit(surv_data)

# We re-count missing values
sapply(merged_data, function(x) sum(is.na(x)))
sapply(surv_data, function(x) sum(is.na(x)))
```

```{r}
# We check the length of each dataset 
length(unique(merged_data$RID)) # longitudinal data
length(unique(surv_data$RID)) # survival data
```

## M2 - Cox PH model with time-averaged biomarkers

```{r}
# Beräkna tidsmedelvärden per individ (RID)
biomarker_avg <- merged_data %>%
  group_by(RID) %>%
  summarise(
    biomarker1_mean = mean(log_PLASMAPTAU181, na.rm = TRUE),
    biomarker2_mean = mean(log_PLASMA_NFL, na.rm = TRUE)
  )
```

```{r}
surv_data <- surv_data %>%
  left_join(biomarker_avg, by = "RID")
```

```{r}
surv_object <- Surv(
  time = surv_data$time_to_event,
  event = surv_data$event
)
```

```{r}
cox_model_bio1 <- coxph(
  surv_object ~ age_at_baseline + APOE4_status + biomarker1_mean,
  data = surv_data
)

summary(cox_model_bio1)
```

```{r}
cox_model_bio2 <- coxph(
  surv_object ~ age_at_baseline + APOE4_status + biomarker2_mean,
  data = surv_data
)

summary(cox_model_bio2)
```
